opt_in_rules:
  - closure_spacing
  - implicitly_unwrapped_optional
  - redundant_type_annotation
  - anonymous_argument_in_multiline_closure
  - balanced_xctest_lifecycle
  - closure_end_indentation
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - file_name
  - file_name_no_space
  - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_interface_builder
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - required_enum_case
  - return_value_from_void_function
  - single_test_class
  - sorted_first_last
  - static_operator
  - switch_case_on_newline
  - test_case_accessibility
  - type_contents_order
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - weak_delegate
  - yoda_condition

analyzer_rules:
  - capture_variable
  - unused_import

included:
 # - Sources
  
excluded:

  - .bundle
  - .git
  - .gitAttributes
  - .gitignore
  - .gitlab
  - Configurations/
  - CONTRIBUTING.md
  - fastlane/
  - Gemfile
  - Gemfile.lock
  - jenkins/
  - logo
  - README.md
  - Resources
  - scripts/
  - Vendor/
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
warning_threshold: 100
unneeded_break_in_switch: error
syntactic_sugar: error
implicit_optional_initialization: error
cyclomatic_complexity:
  warning: 10
  error: 40
  ignores_case_statements: true
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length:
  warning: 250
  error: 500
  ignores_urls: true
  ignores_comments: true
  ignores_function_declarations: true
# they can set both implicitly with an array
type_body_length:
  warning: 500
  error: 1000
# or they can set both explicitly
file_length:
  warning: 1000
  error: 2000
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
  excluded:
   - T
function_body_length:
    warning: 60
    error: 160
function_parameter_count:
  warning: 5
  error: 10
multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true
nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5
large_tuple:
  warning: 5
  error: 5
private_over_fileprivate:
  validate_extensions: true
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
vertical_whitespace:
  max_empty_lines: 2
identifier_name:
  max_length: 50
  min_length: 1
  excluded: # excluded via string array
    - id
    - URL
reporter: "xcode"
disabled_rules:
  - discouraged_optional_boolean
  - blanket_disable_command

